# Generated by Django 2.2 on 2024-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.DateTimeField(),
        ),
    ]
