# Generated by Django 2.2 on 2024-06-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20240626_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={},
        ),
    ]
