# Generated by Django 2.2 on 2024-06-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20240627_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',)},
        ),
    ]
